### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by camoverride** [GaelGil/notebooks#1]
Overall Goal:
- [ ] Write functions that generate features, i.e. book length, average word length, entropy (how predictable is a book's words -- look this up!), etc.
- [ ] Map all these features to a database with the columns `x1, x1, x3, ... , xn, y` and export it.
- [ ] Load this data into a jupyter notebook and apply a logistic regression model to see if you can predict `y` (book genre) from `X` (the book features).

Minutiae:
- [ ] Get more books.
- [ ] Create function to automatically download books given some project gutenberg link.
- [ ] Write all the books to some kind of database (optional)
- [ ] Make sure all your functions are properly documented using [numpy style](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Make sure your `README` describes what's happening.
- [ ] Make sure your notebook is concise, has lots of comments, and useful visualizations.
- [ ] Frequently upload your work to github.

Afterwards:
- Make this into a blog post.
- Expand to using multiple genres.
- Experiment with different features, different datasets, and different models.

**Comment by GaelGil** [comment]
this project has changed to this repo [here](https://github.com/GaelGil/notebooks/tree/master/book_genre_comparison)
